<a href="https://colab.research.google.com/github/gquinche/AlgorithmsUN2021II/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_string1 = 'Bienvenido a'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2) 

Bienvenido a QuantConnect


In [ ]:
my_int = 10
print(my_int)

10


In [ ]:
print(type(my_int))

<class 'int'>


In [ ]:
my_string = "100"
print(type(my_string))

<class 'str'>


In [ ]:
my_int = int(my_string)
print(type(my_int))

<class 'int'>


In [ ]:
my_float = 1.
print(type(my_float))

<class 'float'>


In [ ]:
my_int = 1
print(type(my_int))

<class 'int'>


In [ ]:
my_string = "100"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


In [ ]:
my_bool = False
print(my_bool)
print(type(my_bool))

False
<class 'bool'>


In [ ]:
print("adición ", 1+1)
print("resta ", 5-2)
print("producto ", 2*3)
print("división", 10//2)
print("exponenciación", 2**3)

adición  2
resta  3
producto  6
división 5
exponenciación 8


In [ ]:
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)

['Quant', 'Connect', 1, 2, 3]


In [ ]:
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) - 1])

5
Quant
3


In [ ]:
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'vamos'
print(my_list)

['Quant', 'Connect', 'vamos', 2, 3]


In [ ]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])

['Connect', 1]


In [ ]:
print(my_list[1:])

['Connect', 1, 2, 3]


In [ ]:
print(my_list[:3])

['Quant', 'Connect', 1]


In [ ]:
print(my_list[:3])

['Quant', 'Connect', 1]


In [ ]:
my_list = ['Hola', 'Quant']
my_list.append('Hola')
print(my_list)
my_list.remove('Hola')
print(my_list)

['Hola', 'Quant', 'Hola']
['Quant', 'Hola']


In [ ]:
my_tuple = ('Bienvenida','a','QuantConnect')

In [ ]:
print(my_tuple[1:])

('a', 'QuantConnect')


In [ ]:
crypto_list = ["ETH","BTC","DAI",'BTC','ETH']
crypto_set = set(crypto_list)
print(crypto_set)

{'DAI', 'BTC', 'ETH'}


In [ ]:
my_dic = {"ETH":"ethereum","BTC":"bitcoin","DAI":"unknown"}

In [ ]:
print(my_dic['DAI'])

unknown


In [ ]:
my_dic['DAI'] = 'MakerDAO´s dai'
print(my_dic['DAI'])

MakerDAO´s dai


In [ ]:
print(my_dic.keys())

dict_keys(['ETH', 'BTC', 'DAI'])


In [ ]:
my_str = 'bienvenido a QuantConnect'
print(my_str[10:])

 a QuantConnect


In [ ]:
print("contando el número de e en esta frase".count('e'))
print('el primer lugar en que aparece e en esta frace'.find('e'))
print('todas las a ahora son e'.replace('a','e'))

7
0
todes les e ehore son e


In [ ]:
Time = '2021-10-10 10:32:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date,"con las:", time)
hour = time.split(':')[0]
print(hour)

2021-10-10 con las: 10:32:00
10


In [ ]:
my_time = 'Hour: {}, Minute: {}'.format(10, 32)
print(my_time)

Hour: 10, Minute: 32


In [ ]:
print ('pi es %f' % 3.1416000000000000001)
print('%s a %s' % ('bienvenido', 'quantconnect'))

pi es 3.141600
bienvenido a quantconnect


In [ ]:
print (1 == 0 )  # 1 equals 0
print (1 == 1  )  # 1 equals 1
print (1 != 0   ) # 1 is not equal to 0
print (5 >= 5  )  # 5 is greater than or equal to 5
print (5 >= 6 )   # 5 is greater than or equal to 6

False
True
True
True
False


In [ ]:
print( (3 > 2 or 1 < 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)) )
print (3 > 2 or 1 < 3 and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)) )

False
True


In [ ]:
#if condition1:
    # if condition1 is true, execute the code here
    # and ignore the rest of this if statement
#elif condition2:
    # if condition1 is false, and condition2 is true, execute the code here
    # and ignore the rest of this if statement
#else:
    # if none of the above conditions is True, execute the code here
   

In [ ]:
i = 0
if i == 0: print('i == 0 is verdadero')

i == 0 is True


In [ ]:
p = 1 > 0
q = 2 > 3
if p and q:
    print('p y q son verdad')
elif p and not q:
     print('q es falso')
elif q and not p:
    print ('p es falso')
else:
    print ('Ni p, ni q son verdad')

q is false


In [ ]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [ ]:
for x in [1,2,3,4,5]: print (x)

1
2
3
4
5


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
bad_performing = ['FB']
new_list = []
for stock in stocks:
    if stock not in bad_performing:
        new_list.append(stock)
print (new_list)

['AAPL', 'GOOG', 'IBM', 'F', 'V', 'G', 'GE']


In [ ]:
cubes = []
for i in [1,2,3,4,5]:
    cubes.append(i**3)
print (cubes)

[1, 8, 27, 64, 125]


In [ ]:
foo = [1,2,3,4,5]
cubes = [x**3 for x in foo]
print(cubes)

[1, 8, 27, 64, 125]


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
bad_performing = ['FB']
new_list = [x for x in stocks if x not in bad_performing]
print (new_list)

['AAPL', 'GOOG', 'IBM', 'F', 'V', 'G', 'GE']


In [ ]:
print ( [(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print ([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB']
                                for y in ['F','V','G','GE'] if x[0] != y[0]]) #lista más reducida

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs V', 'FB vs G', 'FB vs GE']


In [ ]:
def product(x,y):
    return x*y
print (product(2,3))
print (product(5,10))

6
50


In [ ]:
def say_hi():
    print ("Bienvenido a QuantConnect")
say_hi()

Bienvenido a QuantConnect


In [ ]:
print ([x for x in range(10)])
print ([x for x in range(1, 11)])
print ([x for x in range(1, 11, 2)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 3, 5, 7, 9]


In [ ]:
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print( "El número de tickers es {}".format(len(tickers)))
for k in range(len(tickers)):
    print (k + 1, tickers[k])

El número de tickers son 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE


In [ ]:
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [ ]:
list(map(lambda x: x**2,range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
list(map(lambda x,y:x+y,["abc","xyz"],["1","2","sin uso"]))

['abc1', 'xyz2']

In [ ]:
sorted(["abc","edf","123"])

['123', 'abc', 'edf']

In [ ]:
price_list = [('Btc', 59), ('ETH', 3.71), ("DAI" , 1)]
sorted(price_list, key = lambda x: x[1])

[('DAI', 1), ('ETH', 3.71), ('Btc', 59)]

In [ ]:
price_list = [('Btc', 59), ('ETH', 3.71), ("DAI" , 1)]
sorted(price_list, key = lambda x: x[1],reverse=True)

[('Btc', 59), ('ETH', 3.71), ('DAI', 1)]

In [ ]:
price_list.sort(key = lambda x: x[0],reverse=True)
print(price_list)

[('ETH', 3.71), ('DAI', 1), ('Btc', 59)]


In [ ]:
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print (self.rate_return)

In [ ]:
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)


In [ ]:
apple.ticker

'AAPL'

In [ ]:
google.print_return()

0.014465338822744034


In [ ]:
google.update(912.8,913.4)
google.print_return()

0.0006573181419806673


In [ ]:
apple.ceo = "Tim cock"

In [ ]:
apple.ceo

'Tim cock'

In [ ]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [ ]:
class Child(Stock):
    def __init__(self, name):
        self.name = name

In [ ]:
aa = Child('AA')
print(aa.name)

AA


In [ ]:
aa.update(100, 102)
print( aa.open)

100


In [ ]:
print(aa.close)

102


In [ ]:
aa.print_return()

0.020000000000000018


In [ ]:
import numpy as np

In [ ]:
price_list = [12,43,6,7,8,1,3]
price_array = np.array(price_list)
print( price_array, type(price_array))

[12 43  6  7  8  1  3] <class 'numpy.ndarray'>


In [ ]:
Ar = np.array([[1,3], [2,4]])
print (Ar, type(Ar))


[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [ ]:
print(Ar.shape)

(2, 2)


In [ ]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [ ]:
np.log(Ar)

array([[0.        , 1.09861229],
       [0.69314718, 1.38629436]])

In [ ]:
np.sum(Ar)


4

In [ ]:
np.std(Ar)

1.118033988749895

In [ ]:

np.mean(Ar)

2.5

In [ ]:

np.max(Ar)

4

In [ ]:
import pandas as pd

In [ ]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print(s)


0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [ ]:
s.index =[6,5,4,3,2,1]
print(s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [ ]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [ ]:
print(s[1:])
print(s[:-2])

b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64
a    143.73
b    145.83
c    143.68
d    144.02
dtype: float64


In [ ]:
print (s["a"])
s["a"] = 0
print (s["a"])

143.73
0.0


In [ ]:
s = pd.Series(price, name = 'Apple Prices')
print (s)
print (s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [ ]:
print(s.describe)

<bound method NDFrame.describe of 0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64>


In [ ]:
time_index = pd.date_range('2021-01-01', periods = len(s), freq = 'D')
print (time_index)


DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')


In [ ]:
s.index = time_index
print (s)

2021-01-01    143.73
2021-01-02    145.83
2021-01-03    143.68
2021-01-04    144.02
2021-01-05    143.50
2021-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [ ]:
s.index = [6,5,4,3,2,1]
print (s)
print (s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [ ]:
print (s.iloc[1])

145.83


In [ ]:
s.index = time_index
print(s['2021-01-03'])


143.68


In [ ]:
print(s['2021-01-02':'2021-01-05'])

2021-01-02    145.83
2021-01-03    143.68
2021-01-04    144.02
2021-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [ ]:
print (s[s < np.mean(s)])
print (s[(s > np.mean(s)) & (s < np.mean(s) + 10*np.std(s))])

2021-01-01    143.73
2021-01-03    143.68
2021-01-05    143.50
2021-01-06    142.62
Name: Apple Prices, dtype: float64
2021-01-02    145.83
2021-01-04    144.02
Name: Apple Prices, dtype: float64


In [ ]:
goo